### PR TITLE
FEAT other base estimators for `AdaBoost`

### LINKED ISSUE #2: support additional base estimators in adaboost estimators
Currently based on `DecisionTreeClassifier` and `DecisionTreeRegressor`.

Support for sample weighting is required, as well as proper classes_ and n_classes_ attributes: see [adaboost docs](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html#sklearn.ensemble.AdaBoostClassifier) and [user guide](http://scikit-learn.org/stable/modules/ensemble.html#adaboost).

### PR DESCRIPTION
**Pull request by valentynbez**
Closes #2.

- `ExtraTree` implemented

- test cases and parameters adapted accordingly

### CODE REVIEW

**Comment by ebolyen** [comment]
@nbokulich would you or someone on your team be able to review this?

**Review by adamovanja — CHANGES_REQUESTED** [review]
hi @valentynbez, thank you for this nice addition :star:. 
The code in `utilities.py`& `plugin_setup.py` looks good to me. 
As for the tests: see my comment inline.

**Comment by adamovanja** [comment]
Hi @valentynbez, it looks like your last commit only adjusted the formatting in the one line 22. I was referring to the formatting in the whole file `test_estimators.py`. As most of the highlighted changes are formatting changes, it's hard to tell where you adjusted the code. You could either revert the formatting or let me know which lines contain the code changes I should review. Thanks 😊

**Comment by valentynbez** [comment]
I see the issue now, I use autoformatters & they did mess up the diff. Please review lines 612-641 & 828-877

**Review by adamovanja — CHANGES_REQUESTED** [review]
It would be great if you could add the two additional assertions suggested inline.

As for the formatting in `test_estimators.py`: This Q2 plugin follows flake8 so I suggest you revert the autoformatting (black?) in this file for consistency. If you feel like black should be a formatting standard in this plugin, please feel free to open a separate PR with respective formatting changes.

**Review by adamovanja — APPROVED** [review]
Hi @valentynbez, Thanks for the edits :star:. LGTM!

**Pull request merged**
