### PR TITLE
WIP : adding in shaply values

### PR DESCRIPTION
**Pull request by mortonjt**
This is a preliminary pull request to add shapely values #219 
Things will probably break for now.

To install this branch, run `pip install git+https://github.com/mortonjt/q2-sample-classifier.git`
Of course, make sure to run `qiime dev refresh-cache` after installation.

### CODE REVIEW

**Comment by lizgehret** [comment]
Hi @mortonjt, thanks for your work on this! Is this something you'd like to see in the 2022.11 release? Our PR submission cutoff is this Friday, so we can get this added to the board if you think it'll be ready for review by Nov. 10th (our PR merge cutoff date).

**Comment by mortonjt** [comment]
Hi Liz, thanks for your interest — unfortunately I don't think we can hit
that deadline. But we can try to hit the next one.

**Comment by lizgehret** [comment]
@mortonjt sounds good! I'll get this added to our future release board. Let us know when it's ready for review. 🙂

**Comment by jindongmin** [comment]
Hi, @mortonjt and I made this work, it was available here https://github.com/jindongmin/q2-sample-classifier.git. Thanks!

**Comment by lizgehret** [comment]
Hey @mortonjt @adamovanja we're going to go ahead and close this PR as well, in conjunction with [this PR](https://github.com/qiime2/q2-sample-classifier/pull/222) that we closed recently. Feel free to reach out if either of you have the bandwidth and interest to pick them back up though!

**Pull request closed without merging**
